name: sanity
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  lottie: ^1.3.0
  flutter_font_icons: ^2.2.5
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  http: ^0.13.4
  shared_preferences: ^2.0.15
  bloc_provider: ^1.0.0
  rxdart: ^0.27.4
  dio: ^4.0.6
  flutter_verification_code: ^1.1.3
  image_picker: ^0.8.5+3
  cross_file_image: ^1.0.0
  persistent_bottom_nav_bar_v2: ^4.2.4
  flutter_icons: ^1.1.0
  intl: ^0.17.0
  timeago: ^3.3.0
  flutter_tts: ^3.5.3
  animated_text_kit: ^4.2.2
  delayed_widget: ^1.1.2
  audioplayers:  any
  loading_animation_widget: ^1.2.0+3
  cached_network_image: ^3.2.1
  firebase_core: ^1.24.0
  basics: ^0.9.0
  cloud_firestore: ^3.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.9
flutter_native_splash:
  color: "#ffffff"
  image: assets/logos/sanity_half.png
  color_dark: "#000000"
  android: true
  ios: true


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/lottie/
    - assets/logos/
    - assets/images/
    - assets/music/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-ExtraLight.ttf #200
        - asset: assets/fonts/Nunito-Light.ttf #300
        - asset: assets/fonts/Nunito-Regular.ttf #400
        - asset: assets/fonts/Nunito-Medium.ttf #500
        - asset: assets/fonts/Nunito-SemiBold.ttf #600
        - asset: assets/fonts/Nunito-Bold.ttf #700
        - asset: assets/fonts/Nunito-ExtraBold.ttf #800
        - asset: assets/fonts/Nunito-Black.ttf #900
    # - family: Trajan Pro
    #   fonts:
    #     - asset: fonts/TrajanPro.ttf
    #     - asset: fonts/TrajanPro_Bold.ttf
    #       weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
