// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbTR4QXTdb6VSdRaM-Ng9oWrheU_kZE30',
    appId: '1:312425398025:web:9e96ba0ed94cc2f81fddd8',
    messagingSenderId: '312425398025',
    projectId: 'sanityhealthapp',
    authDomain: 'sanityhealthapp.firebaseapp.com',
    storageBucket: 'sanityhealthapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXmUrOL8euVAadl41QY4YXAhxW0uIS0Hg',
    appId: '1:312425398025:android:848b45dbb98d72591fddd8',
    messagingSenderId: '312425398025',
    projectId: 'sanityhealthapp',
    storageBucket: 'sanityhealthapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhHKoT7c3EuCad3M7Ufmci4HXrsTWOiA4',
    appId: '1:312425398025:ios:cf32fbe3b53726fe1fddd8',
    messagingSenderId: '312425398025',
    projectId: 'sanityhealthapp',
    storageBucket: 'sanityhealthapp.appspot.com',
    iosClientId: '312425398025-icd4bqgf59qfbd3r19dmg0kjgee2c27i.apps.googleusercontent.com',
    iosBundleId: 'com.example.sanity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhHKoT7c3EuCad3M7Ufmci4HXrsTWOiA4',
    appId: '1:312425398025:ios:cf32fbe3b53726fe1fddd8',
    messagingSenderId: '312425398025',
    projectId: 'sanityhealthapp',
    storageBucket: 'sanityhealthapp.appspot.com',
    iosClientId: '312425398025-icd4bqgf59qfbd3r19dmg0kjgee2c27i.apps.googleusercontent.com',
    iosBundleId: 'com.example.sanity',
  );
}
